# Generated by Django 3.2.9 on 2021-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
